---
- name: Log on which Linux distro Docker is going to be installed
  debug:
    msg: "The distro is: {{ ansible_distribution|lower }} and the version name is: {{ ansible_distribution_release }}"

- name: Install needed packages (see https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - libffi-dev
    allow_unauthenticated: true
    install_recommends: no
    state: latest

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker apt repo (as shown in step 4 of https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository in armhf)
  shell: |
    echo "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution|lower }} \
    {{ ansible_distribution_release }} stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list
  become: true

- name: Install Docker apt package
  apt:
    pkg: docker-ce
    state: latest
    update_cache: yes
    install_recommends: no

- name: Install pip
  apt:
    name:
      - python-pip
      - python-setuptools
    state: latest

- name: Remove pip's backports (See https://github.com/docker/docker-py/issues/1502#issuecomment-506544849)
  pip:
    name: backports.ssl-match-hostname
    state: absent

- name: Install debian's backports
  apt:
    name:
      - python-backports.ssl-match-hostname
    install_recommends: no

- name: Install Docker Compose
  pip:
    name: docker-compose

- name: add pi user to docker group
  user:
    name: pi
    groups: docker
    append: yes
  become: true